package main

import (
	"fmt"
	"go/ast"
	"io"
	"time"
)

// Draw the package graph into the provided file
func DrawPackages(of io.Writer, pkgs map[string]*ast.Package) {

	fmt.Fprintln(of, "// Autogenerated on ", time.Now())

	fmt.Fprintln(of, "strict digraph {")
	defer fmt.Fprintln(of, "}")

	for _, p := range pkgs {
		for _, ff := range p.Files {
			for _, imp := range ff.Imports {
				fmt.Fprintf(of, "%q -> %s\n", p.Name, imp.Path.Value)
			}
		}
	}

}
